using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Da単oBala : MonoBehaviour
{
    [SerializeField] int da単o;
    [SerializeField] AudioManager sfx;

    public void Start()
    {
        sfx = GameObject.FindGameObjectWithTag("AudioManager").GetComponent<AudioManager>();
    }

    private void OnCollisionEnter(Collision collision)
    {
        VidaAsteroides asteroide = collision.rigidbody.GetComponent<VidaAsteroides>();
        if (asteroide != null)
        {
            sfx.PlaySFX("Impacto");

            asteroide.Da単oRecibido(da単o);

            Destroy(this.gameObject);

        }
    }

}
